apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: filemonitors.sentinalfs.io
spec:
  group: sentinalfs.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              path:
                type: string
                description: "The file system path to monitor"
              namespace:
                type: string
                description: "The namespace this monitor belongs to"
            required:
            - path
            - namespace
          status:
            type: object
            properties:
              files:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    inode:
                      type: integer
                      format: int64
                    size:
                      type: integer
                      format: int64
                    modTime:
                      type: string
                      format: date-time
                    path:
                      type: string
                    isDir:
                      type: boolean
                  required:
                  - name
                  - inode
                  - size
                  - modTime
                  - path
                  - isDir
  scope: Namespaced
  names:
    plural: filemonitors
    singular: filemonitor
    kind: FileMonitor
